# Pipeline for calculating ABC score for candidate Sox9 enhancers in MC and FL (See Methods for detailed information).

# Input for calculating ABC score includes:
# 1. Preparation of candidate Sox9 enhancers, which could be generated by using the “makeCandidateRegions.py” script provided in the ABC model;
# 2. Activities of candadate Sox9 enhancers, which could be performed with "run.neighborhoods.py" script provided in the ABC model;
# 3. Interaction frequency matrix at Sox9 region extracted from cool files

# Remove genic/promoter enhancers, keep intergenic enhancers
python Remove_genic_enhancers.py
# Combine enhancer activity and contact matrix
bedtools intersect -a MC_enhancer_activity.bed -b MC_contact.bed -wao > MC_enhancer_contact.bed
bedtools intersect -a FL_enhancer_activity.bed -b FL_contact.bed -wao > FL_enhancer_contact.bed
# Calculate ABC score
python Calculate_ABC.py 
# Compare ABC score between MC and FL
bedtools intersect -a MC_ABC_score.bed -b FL_ABC_score.bed -wao > MC_vs_FL_ABC_score.bed 
python ABC_MC_minus_FL.py